# Description: Travis CI configuration file for the staticweb project
os: linux
dist: xenial
language: generic

services:
  - docker


script:
  - docker ps -a

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t "filipdadgar/staticweb" .
  - docker push "filipdadgar/staticweb"