os: linux
dist: xenial
language: generic

services:
  - docker

after_success:
  - docker build -t "filipdadgar/static-web" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push "filipdadgar/static-web:latest"
  - echo "done pushing!"